### ISSUE TITLE
这个机制在容器使用privileged 模式下是否正常？

### ISSUE THREAD

**Issue by davidstack** [laincloud/entry#6]
运行两个同样的容器
docker run -itd --privileged -e "container=docker" -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos:7.1.1503 /usr/sbin/init

使用websocket进行连接是否正常？getty进程占用的cpu是否为100%呢？

**Comment by ericpai** [comment]
不是很明白你的场景。这个应用在实际环境下测试工作是正常的，且进入的容器都是单进程容器。从你的这个命令上来看，你是在容器里又启动了一套内核？

**Comment by davidstack** [comment]
有没有存在两个getty进程？我这个问题解决了，需要在镜像中禁掉getty服务

**Comment by ericpai** [comment]
这个应用并没有在这种环境下测试过，终端都是通过Docker的API打开的，和容器中是否有getty应该没有关系
